apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://myapp.local 
  APP_KEY: base64:DnCcX/IKoB9hASFxAGINSFGHC+pAUtNZ9oWDtafqBhE=
  LOG_CHANNEL: stack
  CORS_ALLOWED_ORIGINS: http://myapp.local 