apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque # Tipe secret generik
data:
  # Konfigurasi untuk MySQL
  MYSQL_ROOT_PASSWORD: U2VjcmV0MTIzIQ== # Contoh: YWRtaW4= (admin)
  MYSQL_DATABASE: c2Vwb3J0X2Ri   # Contoh: YXBwX2Ri (app_db)
  MYSQL_USER: YWRtaW4=              # Contoh: YXBwX3VzZXI= (app_user)
  MYSQL_PASSWORD: U2VjcmV0MTIzIQ==          # Contoh: c2VjcmV0 (secret)

  # Untuk konfigurasi Laravel
  DB_DATABASE: c2Vwb3J0X2Ri        # Sama dengan MYSQL_DATABASE
  DB_USERNAME: YWRtaW4=              # Sama dengan MYSQL_USER
  DB_PASSWORD: U2VjcmV0MTIzIQ==             # Sama dengan MYSQL_PASSWORD
  DB_HOST: bXlzcWwtc2VydmljZQ==                              # base64("mysql-service")
  DB_PORT: MzMwNg==                                          # base64("3306")