apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce # Hanya dapat di-mount oleh satu Node dalam mode baca-tulis
  resources:
    requests:
      storage: 1Gi # Meminta 1 Gigabyte penyimpanan