server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Mengizinkan CORS jika diperlukan
    # add_header 'Access-Control-Allow-Origin' '*'; # Sesuaikan dengan origin frontend Anda
    # add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    # add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    # add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

    location / {
        try_files $uri $uri/ /index.html; # Penting untuk aplikasi SPA React
    }

    # Jika Anda ingin meneruskan panggilan API langsung melalui Nginx frontend
    # (opsional, karena Ingress akan menangani ini)
    # location /api/ {
    #     proxy_pass http://backend-service:80; # Nama service backend Kubernetes
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    error_page 404 /index.html; # U
}